# Generated by Django 3.1.1 on 2022-12-14 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gitdata',
            old_name='username',
            new_name='username_primary_key',
        ),
    ]
