# Generated by Django 3.1.1 on 2022-12-14 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitdata', '0002_auto_20221214_2233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GitData',
            new_name='GitDatabase',
        ),
    ]
